### PR TITLE
Preliminary editorial suggestions

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- consolidate normative references

## Notes

Maybe there's some editorial work to do to improve the spec.

### CODE REVIEW

**Comment by Kevsy** [comment]
Many thanks for your review @ioggstream - all agreed and merged. I'll wait for the outcome of [the discussion](https://mailarchive.ietf.org/arch/msg/httpapi/5GiOAMPrkmwstnKUBjS7IntGQ0s/) regarding a mandatory media type before releasing a new version.

**Comment by ioggstream** [comment]
Thanks @Kevsy ! I still need to think about a mandatory media type.

As a hint, I suggest you to brush the document according to https://httpwg.org/admin/editors/style-guide

I just did a preliminary PR.

Thanks for your efforts on this topic!

**Comment by Kevsy** [comment]
Ah, I ran out out of time to do the document 'brush' before submitting the response to the AD review - but I will make sure to take it into account for the subsequent version.

**Comment by richsalz** [comment]
It's okay.  Minor editorial things can happen during IESG review, IETF Last call, RFC-Editor interactions, etc.

**Pull request merged**
